# Generated by Django 3.2.7 on 2023-04-21 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
                ('Contact', models.CharField(max_length=50)),
                ('Dob', models.CharField(max_length=50)),
                ('Gender', models.CharField(max_length=50)),
            ],
        ),
    ]
