# Generated by Django 3.2.7 on 2023-04-23 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_full_name_customer_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank_money',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bank_name', models.CharField(max_length=50)),
                ('Account_name', models.CharField(max_length=90)),
                ('Ifsc_code', models.CharField(max_length=50)),
                ('Bank_amount', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Deposie_moeny',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.CharField(max_length=76)),
            ],
        ),
        migrations.CreateModel(
            name='Upi_money',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Upi_deatails', models.CharField(max_length=50)),
                ('Upi_amount', models.CharField(max_length=50)),
            ],
        ),
    ]
