# Generated by Django 3.2.7 on 2023-04-24 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_bank_money_deposie_moeny_upi_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank_money',
            name='Bank_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='upi_money',
            name='Upi_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
