# Generated by Django 3.2.7 on 2023-04-27 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20230427_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Balance',
            field=models.CharField(default=1, max_length=90),
            preserve_default=False,
        ),
    ]
