# Generated by Django 3.2.7 on 2023-04-27 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_customer_balance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bank_money',
        ),
        migrations.DeleteModel(
            name='Deposie_moeny',
        ),
        migrations.DeleteModel(
            name='Upi_money',
        ),
    ]
