# Generated by Django 3.2.7 on 2023-04-27 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20230427_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Balance',
            field=models.CharField(default='500', max_length=90),
        ),
    ]
