# Generated by Django 3.2.7 on 2023-04-27 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_customer_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Balance',
            field=models.IntegerField(default=600),
        ),
    ]
