# Generated by Django 3.2.7 on 2023-05-12 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_auto_20230427_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Balance',
            field=models.IntegerField(default=500),
        ),
    ]
